_target_: hulc.datasets.shm_dataset_skip.ShmDatasetSkip
key: "lang"
save_format: "npz"
batch_size: 32
min_window_size: 32
max_window_size: 64
effective_min_ws: 20
effective_max_ws: 32
proprio_state: ${datamodule.proprioception_dims}
obs_space: ${datamodule.observation_space}
skip_frames: 1
pad: true
lang_folder: "lang_annotations"
aux_lang_loss_window: 8
num_workers: 2
pos_threshold: 0.99
orn_threshold: 0.08
skip_strategy: "random"
min_skip_ratio: 0
max_skip_ratio: 0.3
