_target_: hulc.models.perceptual_encoders.vision_network_gripper.VisionNetwork
input_width: 84
input_height: 84
activation_function: ReLU #ELU
dropout_vis_fc: 0.0
l2_normalize_output: false
visual_features: 64
conv_encoder: nature_cnn
num_c: 1
