_target_: hulc.models.decoders.clip_proj.ClipProj
im_dim: ${model.plan_recognition.fc_hidden_size}
lang_dim: ${model.language_goal.latent_goal_features}
output_dim: ${model.language_goal.latent_goal_features}
proj_lang: true
